# Generated by Django 5.2.13 on 2026-09-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
