# Generated by Django 5.2.13 on 2026-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
