# Generated by Django 5.2.13 on 2026-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('ACCOUNT_CREATION', 'Account Creation'), ('DEV_CENTER_BOOKING', 'Dev Center Booking')], default='ACCOUNT_CREATION', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=32),
        ),
    ]
